# Generated by Django 6.0.6 on 2026-07-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('suite', 'Suite'), ('standard', 'Standard'), ('deluxe', 'Deluxe')], max_length=100)),
                ('pricePerNight', models.IntegerField(default=150)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('USD', 'EUR')], default='USD', max_length=10)),
                ('maxOccupancy', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='booking_app.room')),
            ],
        ),
    ]
